#   exclude:
#     - path/to/excluded/files/**

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    cancel_subscriptions: true
    hash_and_equals: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    test_types_in_equals: true
    unrelated_type_equality_checks: true
    valid_regexps: true
